package com.xjgj.mall.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.xjgj.mall.db.Test;
import com.xjgj.mall.db.Destination;

import com.xjgj.mall.db.TestDao;
import com.xjgj.mall.db.DestinationDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig testDaoConfig;
    private final DaoConfig destinationDaoConfig;

    private final TestDao testDao;
    private final DestinationDao destinationDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        testDaoConfig = daoConfigMap.get(TestDao.class).clone();
        testDaoConfig.initIdentityScope(type);

        destinationDaoConfig = daoConfigMap.get(DestinationDao.class).clone();
        destinationDaoConfig.initIdentityScope(type);

        testDao = new TestDao(testDaoConfig, this);
        destinationDao = new DestinationDao(destinationDaoConfig, this);

        registerDao(Test.class, testDao);
        registerDao(Destination.class, destinationDao);
    }
    
    public void clear() {
        testDaoConfig.getIdentityScope().clear();
        destinationDaoConfig.getIdentityScope().clear();
    }

    public TestDao getTestDao() {
        return testDao;
    }

    public DestinationDao getDestinationDao() {
        return destinationDao;
    }

}
