package com.xjgj.mall.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DESTINATION.
 */
public class Destination {

    private Long id;
    /** Not-null value. */
    private String termini;

    public Destination() {
    }

    public Destination(Long id) {
        this.id = id;
    }

    public Destination(Long id, String termini) {
        this.id = id;
        this.termini = termini;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTermini() {
        return termini;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTermini(String termini) {
        this.termini = termini;
    }

}
